services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wt-db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'PG_DATA=/var/lib/postgresql/data/pgdata'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    ports:
      - '5432'
