// This file is auto-generated by @hey-api/openapi-ts

export const $Exercise = {
    required: ['lbs', 'name', 'reps', 'sets'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        lbs: {
            type: 'integer',
            format: 'int32'
        },
        reps: {
            type: 'integer',
            format: 'int32'
        },
        sets: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const $Workout = {
    required: ['date', 'exercises'],
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date'
        },
        exercises: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Exercise'
            }
        }
    }
} as const;