// This file is auto-generated by @hey-api/openapi-ts

export type Exercise = {
    name: string;
    lbs: number;
    reps: number;
    sets: number;
};

export type Workout = {
    date: string;
    exercises: Array<Exercise>;
};

export type GetWorkoutByDateData = {
    date: string;
};

export type GetWorkoutByDateResponse = Workout;

export type UpdateWorkoutData = {
    requestBody: Workout;
};

export type UpdateWorkoutResponse = unknown;

export type AddWorkoutData = {
    requestBody: Workout;
};

export type AddWorkoutResponse = unknown;

export type RemoveWorkoutByDateData = {
    date: string;
};

export type RemoveWorkoutByDateResponse = void;

export type GetAllWorkoutsResponse = Array<Workout>;

export type GetExerciseByNameData = {
    name: string;
};

export type GetExerciseByNameResponse = unknown;

export type GetExercisesResponse = Array<Exercise>;

export type $OpenApiTs = {
    '/api/workout': {
        get: {
            req: GetWorkoutByDateData;
            res: {
                /**
                 * Ok - Workout was found for given date
                 */
                200: Workout;
                /**
                 * Not Found - Workout was not found for given date
                 */
                404: unknown;
            };
        };
        put: {
            req: UpdateWorkoutData;
            res: {
                /**
                 * Ok - Workout was successfully updated
                 */
                default: unknown;
            };
        };
        post: {
            req: AddWorkoutData;
            res: {
                /**
                 * Created - Workout was created successfully
                 */
                201: unknown;
                /**
                 * Bad Request - Workout already exists for specified date
                 */
                400: unknown;
            };
        };
        delete: {
            req: RemoveWorkoutByDateData;
            res: {
                /**
                 * No Content - Workout was removed successfully
                 */
                204: void;
                /**
                 * Bad Request - Date was missing or invalid
                 */
                400: unknown;
                /**
                 * Not Found - Workout was not found for specified date
                 */
                404: unknown;
            };
        };
    };
    '/api/workout/all': {
        get: {
            res: {
                /**
                 * Ok - All workouts were retrieved successfully
                 */
                default: Array<Workout>;
            };
        };
    };
    '/api/exercise': {
        get: {
            req: GetExerciseByNameData;
            res: {
                /**
                 * Ok - exercise was retrieved successfully
                 */
                200: unknown;
                /**
                 * Not Found - Exercise with that name does not exist
                 */
                404: unknown;
            };
        };
    };
    '/api/exercise/all': {
        get: {
            res: {
                /**
                 * Ok - exercise were received successfully
                 */
                200: Array<Exercise>;
            };
        };
    };
};