name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Cache Maven Repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2
      - name: Setup Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build jar
        run: ./mvnw package
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag workout-tracker:$(date +%s)

  deploy:
    needs:
      build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Deploy Code Changes
        run: |
          echo "Creating SSH Key file"
          echo -n "${SSH_DEPLOY_KEY}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          
          echo "Verifying SSH Key file"
          ssh-keygen -l -f /tmp/ssh_key
          
          echo "Creating ENV file"
          echo "POSTGRES_USER: ${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASS: ${POSTGRES_PASS}" >> .env
          echo "POSTGRES_DB: ${POSTGRES_DB}" >> .env
          echo "API_DOMAIN: workout.burchbytes.com" >> .env
          
          echo "Deploying ENV file"
          scp -o StrictHostKeyChecking=no -i /tmp/ssh_key .env github@workout.burchbytes.com:.env
          
          echo "Running Deploy script"
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key github@workout.burchbytes.com bash < ./scripts/deploy.sh

        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS: ${{ secrets.POSTGRES_PASS }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          
