name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        uses: actions/checkout@v4
        env:
            SSH_DEPLOY_KEY = ${{ secrets.SSH_DEPLOY_KEY }}
        run: |
          touch /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          echo ${SSH_DEPLOY_KEY} > /tmp/ssh_key
          ssh github@workout.burchbytes.com bash < ./scripts/deploy.sh
